####Name : Lokendra J. Sinha
####Roll No : 32-A
####Branch : AIML
####Date : 27/06/2025

In [2]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
s1_1 = pd.Series([10, 20, 30, 40, 50])
print(s1_1)
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print(np_array1_2)
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.
df1_3 = pd.DataFrame(np_array1_2, columns=['A','B','C','D'])
print(df1_3)
print(df1_3.head(3))

# Your code for Task 1 here:



# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

dates = pd.date_range(start='2023-01-01', end='2023-04-09', freq='D')
regions = ['East', 'West', 'North', 'South']
products = ['Laptop', 'Mouse', 'Keyboard', 'Monitor']

df_sales = pd.DataFrame({
    'Date': np.random.choice(dates, 100, replace=True),
    'Region': np.random.choice(regions, 100),
    'Product': np.random.choice(products, 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})

# Introduce NaN values
nan_indices = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[nan_indices, 'Sales'] = np.nan

nan_indices = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[nan_indices, 'Quantity'] = np.nan

# Your code for Task 2 here:






# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
df3_1 = df_sales[['Region', 'Sales']]
print(df3_1)
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print(df3_2)
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
print(df3_3)
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]
print(val3_4)

# Your code for Task 3 here:



# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs)

# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
missing_counts4_1 = df_sales.isnull().sum()
print(missing_counts4_1)
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean(), inplace=True)
print(df4_2_filled)
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.
df4_3_dropped = df_sales.dropna()
print(df4_3_dropped)

# Your code for Task 4 here:



# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
print(df_sales)
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])
print(df5_2_sorted)
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
df5_3_grouped_region = df_sales.groupby('Region').agg({'Sales': 'sum', 'Quantity': 'sum'})
print(df5_3_grouped_region)
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()
print(df5_4_grouped_product)

# Your code for Task 5 here:


--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[98 96 89 85]
 [30 60 85 16]
 [93 53 25 95]]
    A   B   C   D
0  98  96  89  85
1  30  60  85  16
2  93  53  25  95
    A   B   C   D
0  98  96  89  85
1  30  60  85  16
2  93  53  25  95

--- Task 2: Synthetic Data Generation for Practice ---

--- Task 3: Indexing and Slicing in DataFrames ---
   Region  Sales
0    West  136.0
1    East  612.0
2    East    NaN
3    East  116.0
4   South    NaN
..    ...    ...
95  South  366.0
96  South  741.0
97   East  861.0
98   East  920.0
99  North  904.0

[100 rows x 2 columns]
         Date Region Product  Sales  Quantity
2  2023-03-07   East  Laptop    NaN       6.0
6  2023-02-27   East  Laptop  688.0       4.0
10 2023-02-16  South  Laptop  865.0       5.0
18 2023-01-29  South  Laptop  

/tmp/ipython-input-2-2850834798.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean(), inplace=True)
