####Name : Lokendra Sinha
####Roll No : 32 - A
####Branch : CSE(AIML)
####Date : 27/06/2025

In [ ]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
# Your code for Task 1 here:
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(100)
print(arr1_1)
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3,3))
print(arr1_2)
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2,4),7)
print(arr1_3)
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10,51,size=(5,5))
print(arr1_4)


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])


# Your code for Task 2 here:
# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
val2_1 = data[2,3]
print("element at(2,3) : ",val2_1)
# 2.2 Extract the first row. Store it in 'row2_2'.
row2_2 = data[0]
print("first row : ",row2_2)
# 2.3 Extract the last column. Store it in 'col2_3'.
col2_3 = data[:3]
print("last column : ",col2_3)
# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
sub_arr2_4 = data[1:3,0:2]
print("sub array : ",sub_arr2_4)
# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.
mask = data >100
filtered_elements2_5 = data[mask]
print("filtered elements : ",filtered_elements2_5)





# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20
print("arr3_1:\n", arr3_1)

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
print("arr3_2:\n", arr3_2)
# 3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.
even_array = arr3_1[arr3_1%2==0]
even_count3_3 = len(even_array)
print("even count : ",even_count3_3)
# Your code for Task 3 here:



# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
print("arr4_1:\n", arr4_1)

# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.
sum4_1 = np.sum(arr4_1)
print("sum : ",sum4_1)
# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.
mean_cols4_2 = np.mean(arr4_1,axis=0)
print("mean of columns : ",mean_cols4_2)
# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.
max_rows4_3=  np.max(arr4_1,axis=1)
print("max of rows : ",max_rows4_3)
# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'.
std4_4 = np.std(arr4_1)
print("standard deviation : ",std4_4)
# Your code for Task 4 here:



# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23
print("arr5_1:\n", arr5_1)

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
reshaped_arr5_2 = arr5_1.reshape(4,6)
print("reshaped array : ",reshaped_arr5_2)
# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
reshaped_arr5_3 = arr5_1.reshape(2,3,4)
print("reshaped array : ",reshaped_arr5_3)
# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
flattened_arr5_4 = reshaped_arr5_2.flatten()
print("flattened array using flatten() : ",flattened_arr5_4)
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).
ravel_arr5_4 = reshaped_arr5_2.ravel()
print("flattened array using ravel() : ",ravel_arr5_4)
# Your code for Task 5 here:



# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
result6_1 = arr6_1+scalar
print("result : ",result6_1)
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_2 = arr6_1+vector
print("result : ",result6_2)

# Your code for Task 6 here:



# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
view_arr7 = original_arr7[:]
print("view array : ",view_arr7)
#     Modify the first element of 'view_arr7' to 99.
view_arr7[0] = 99
print("view array : ",view_arr7)
#     Observe how 'original_arr7' changes.

print("original array : ",original_arr7)
# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
copy_arr7 = original_arr7.copy()
print("copy array : ",copy_arr7)
#     Modify the last element of 'copy_arr7' to 0.
copy_arr7[-1] = 0
print("copy array : ",copy_arr7)
#     Observe how 'original_arr7' remains unchanged.
print("original array : ",original_arr7)

# Your code for Task 7 here:



# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
vstack_arr8_1 = np.vstack((arr8_a,arr8_b))
print("vertically stacked array : ",vstack_arr8_1)
# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
hstack_arr8_2 = np.hstack((arr8_a,arr8_b))
print("horizontally stacked array : ",hstack_arr8_2)
# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
combined_arr8_3 = np.vstack((vstack_arr8_1,arr8_c))
print("combined array : ",combined_arr8_3)
# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.
part1,part2,part3 = np.vsplit(combined_arr8_3,[2,4])
print("part1 : ",part1)
print("part2 : ",part2)
print("part3 : ",part3)

# Your code for Task 8 here:



# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
print("arr9_1:\n", arr9_1)
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])
print("arr9_2d:\n", arr9_2d)

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
sorted_arr9_1 = np.sort(arr9_1)
print("sorted array : ",sorted_arr9_1)
# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
sorted_cols9_2 = np.sort(arr9_2d,axis=0)
print("sorted array : ",sorted_cols9_2)
# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
idx9_3 = np.where(arr9_1==9)
print("indices : ",idx9_3)
# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.
max_idx9_4 = np.argmax(arr9_1)
print("max index : ",max_idx9_4)
# Your code for Task 9 here:


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]
[[49 17 32 48 14]
 [15 34 18 44 30]
 [35 15 20 30 24]
 [37 22 47 24 10]
 [22 15 49 25 41]]
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[49 17 32 48 14]
 [15 34 18 44 30]]

--- Task 2: Indexing and Slicing with Arrays ---
element at(2,3) :  120
first row :  [10 20 30 40]
last column :  [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
sub array :